
package uni.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sun Apr 11 17:05:52 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "addUniversity", namespace = "http://service.webservice.uni/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addUniversity", namespace = "http://service.webservice.uni/")

public class AddUniversity {

    @XmlElement(name = "university")
    private uni.webservice.model.University university;

    public uni.webservice.model.University getUniversity() {
        return this.university;
    }

    public void setUniversity(uni.webservice.model.University newUniversity)  {
        this.university = newUniversity;
    }

}

