
package uni.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Apr 16 16:37:44 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getAllUniversitiesResponse", namespace = "http://service.webservice.uni/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllUniversitiesResponse", namespace = "http://service.webservice.uni/")

public class GetAllUniversitiesResponse {

    @XmlElement(name = "universities")
    private uni.webservice.model.University[] universities;

    public uni.webservice.model.University[] getUniversities() {
        return this.universities;
    }

    public void setUniversities(uni.webservice.model.University[] newUniversities)  {
        this.universities = newUniversities;
    }

}

