
package uni.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Apr 16 16:37:44 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getSpecialitytoUni", namespace = "http://service.webservice.uni/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getSpecialitytoUni", namespace = "http://service.webservice.uni/", propOrder = {"id_u", "id_s"})

public class GetSpecialitytoUni {

    @XmlElement(name = "id_u")
    private int id_u;
    @XmlElement(name = "id_s")
    private int id_s;

    public int getId_u() {
        return this.id_u;
    }

    public void setId_u(int newId_u)  {
        this.id_u = newId_u;
    }

    public int getId_s() {
        return this.id_s;
    }

    public void setId_s(int newId_s)  {
        this.id_s = newId_s;
    }

}

